#!/bin/bash
#
# Local dev setup for docs-graph (REPO MAINTAINERS ONLY)
#
# This script is for people cloning this repo to develop the plugin itself.
# End users who installed docs-graph via the Cowork marketplace do NOT need
# to run this — the build-graph skill bootstraps _graph/, docs/, and data/
# automatically in the user's mounted folder.
#
# What this does: symlinks your real docs and data into this repo at
# ./docs/ and ./data/ so you can develop against real content. _graph/ is
# NOT symlinked — it gets regenerated by build.py.
#
# Usage:
#   ./setup.sh                                    # docs/ → ~/docs, data/ → ~/data
#   ./setup.sh ~/other/docs                       # docs/ → custom path, data/ → ~/data
#   ./setup.sh ~/other/docs ~/other/data          # both custom
#

set -e
cd "$(dirname "$0")"

DOCS_TARGET="${1:-$HOME/docs}"
DATA_TARGET="${2:-$HOME/data}"

# ── docs/ symlink ──
if [ -L "docs" ]; then
    echo "docs/ symlink already exists → $(readlink docs)"
elif [ -d "docs" ]; then
    echo "docs/ directory already exists (not a symlink). Skipping."
else
    DOCS_TARGET="$(cd "$DOCS_TARGET" 2>/dev/null && pwd || echo "$DOCS_TARGET")"
    if [ ! -d "$DOCS_TARGET" ]; then
        echo "Target directory doesn't exist: $DOCS_TARGET"
        echo "Create it first or pass a different path."
        exit 1
    fi
    ln -s "$DOCS_TARGET" docs
    echo "Symlinked docs/ → $DOCS_TARGET"
fi

# ── data/ symlink ──
if [ -L "data" ]; then
    echo "data/ symlink already exists → $(readlink data)"
elif [ -d "data" ]; then
    echo "data/ directory already exists (not a symlink). Skipping."
else
    DATA_TARGET="$(cd "$DATA_TARGET" 2>/dev/null && pwd || echo "$DATA_TARGET")"
    if [ ! -d "$DATA_TARGET" ]; then
        echo "No data/ target found at $DATA_TARGET — skipping (data/ is optional)."
    else
        ln -s "$DATA_TARGET" data
        echo "Symlinked data/ → $DATA_TARGET"
    fi
fi

# ── Skills symlink ──
SKILLS_SRC="$(cd "$(dirname "$0")" && pwd)/skills"

for agent_dir in ~/.cursor/skills ~/.claude/skills ~/.codex/skills; do
    [ -d "$(dirname "$agent_dir")" ] || continue
    mkdir -p "$agent_dir"
    for skill in "$SKILLS_SRC"/*/; do
        [ -d "$skill" ] || continue
        skill_name=$(basename "$skill")
        ln -sfn "$skill" "$agent_dir/$skill_name"
    done
    echo "Linked docs-graph skills into $agent_dir/"
done

echo ""
echo "Next steps:"
echo "  1. Use the create-doc skill to add documents to docs/"
echo "  2. Use the build-graph skill to generate _graph/"
echo "  3. Open _graph/index.html in a browser to see the graph"
