#!/bin/bash
#
# Local dev setup for docs-graph (REPO MAINTAINERS ONLY)
#
# This script is for people cloning this repo to develop the plugin itself.
# End users who installed docs-graph via the Cowork marketplace do NOT need
# to run this — the build-graph skill bootstraps _graph/, docs/, and data/
# automatically in the user's mounted folder.
#
# What this does: symlinks your real docs and data into this repo at
# ./docs/ and ./data/ so you can develop against real content. _graph/ is
# NOT symlinked — it gets regenerated by build.py.
#
# Usage:
#   ./setup.sh                                    # docs/ → ~/docs, data/ → ~/data
#   ./setup.sh ~/other/docs                       # docs/ → custom path, data/ → ~/data
#   ./setup.sh ~/other/docs ~/other/data          # both custom
#

set -e
cd "$(dirname "$0")"

# Resolve the developer's real home. On a regular host this is just $HOME.
# Inside a Cowork sandbox, $HOME is /sessions/<session-id>/ and the user's
# actual files are mounted at $HOME/mnt/<username>/, so use that instead.
DEV_HOME="$HOME"
if [[ "$HOME" == /sessions/* ]] && [ -d "$HOME/mnt" ]; then
    for mount_dir in "$HOME"/mnt/*/; do
        if [ -d "$mount_dir" ]; then
            DEV_HOME="${mount_dir%/}"
            break
        fi
    done
fi

DOCS_TARGET="${1:-$DEV_HOME/docs}"
DATA_TARGET="${2:-$DEV_HOME/data}"

# ── docs/ symlink ──
# Always refresh the symlink so the script is safe to re-run every session.
# Cowork sandbox mount paths (/sessions/<session-id>/...) change between
# sessions, so a previously-created symlink will often be stale. Only skip
# if docs/ is a real directory — we don't want to clobber a real folder.
if [ -d "docs" ] && [ ! -L "docs" ]; then
    echo "docs/ is a real directory (not a symlink). Skipping."
else
    DOCS_TARGET="$(cd "$DOCS_TARGET" 2>/dev/null && pwd || echo "$DOCS_TARGET")"
    if [ ! -d "$DOCS_TARGET" ]; then
        echo "Target directory doesn't exist: $DOCS_TARGET"
        echo "Create it first or pass a different path."
        exit 1
    fi
    ln -sfn "$DOCS_TARGET" docs
    echo "Symlinked docs/ → $DOCS_TARGET"
fi

# ── data/ symlink ──
if [ -d "data" ] && [ ! -L "data" ]; then
    echo "data/ is a real directory (not a symlink). Skipping."
else
    DATA_TARGET="$(cd "$DATA_TARGET" 2>/dev/null && pwd || echo "$DATA_TARGET")"
    if [ ! -d "$DATA_TARGET" ]; then
        echo "No data/ target found at $DATA_TARGET — skipping (data/ is optional)."
    else
        ln -sfn "$DATA_TARGET" data
        echo "Symlinked data/ → $DATA_TARGET"
    fi
fi

# ── Skills symlink ──
SKILLS_SRC="$(cd "$(dirname "$0")" && pwd)/skills"

for agent_dir in ~/.cursor/skills ~/.claude/skills ~/.codex/skills; do
    [ -d "$(dirname "$agent_dir")" ] || continue
    mkdir -p "$agent_dir"
    for skill in "$SKILLS_SRC"/*/; do
        [ -d "$skill" ] || continue
        skill_name=$(basename "$skill")
        ln -sfn "$skill" "$agent_dir/$skill_name"
    done
    echo "Linked docs-graph skills into $agent_dir/"
done

echo ""
echo "Next steps:"
echo "  1. Use the create-doc skill to add documents to docs/"
echo "  2. Use the build-graph skill to generate _graph/"
echo "  3. Open _graph/index.html in a browser to see the graph"
