#!/bin/bash
#
# Local dev setup for docs-graph
#
# Creates a symlink so your real docs appear at ./docs/ for local development.
# The _graph/ folder is NOT symlinked — it gets regenerated by build-graph.
#
# Usage:
#   ./setup.sh                         # symlinks docs/ → ~/docs (default)
#   ./setup.sh ~/other/docs            # symlinks docs/ → custom path
#

set -e
cd "$(dirname "$0")"

DOCS_TARGET="${1:-$HOME/docs}"

if [ -L "docs" ]; then
    echo "docs/ symlink already exists → $(readlink docs)"
    echo "Remove it first if you want to change the target: rm docs"
    exit 0
fi

if [ -d "docs" ]; then
    echo "docs/ directory already exists (not a symlink). Nothing to do."
    exit 0
fi

# Resolve to absolute path
DOCS_TARGET="$(cd "$DOCS_TARGET" 2>/dev/null && pwd || echo "$DOCS_TARGET")"

if [ ! -d "$DOCS_TARGET" ]; then
    echo "Target directory doesn't exist: $DOCS_TARGET"
    echo "Create it first or pass a different path."
    exit 1
fi

ln -s "$DOCS_TARGET" docs
echo "Symlinked docs/ → $DOCS_TARGET"

echo ""
echo "Next steps:"
echo "  1. Use the create-doc skill to add documents to docs/"
echo "  2. Use the build-graph skill to generate _graph/"
echo "  3. Open _graph/index.html in a browser to see the graph"
